# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.
import os
import sys

# Đảm bảo plugin Qt được tìm thấy trên các hệ thống khác nhau
if hasattr(sys, '_MEIPASS'):
    os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = os.path.join(sys._MEIPASS, 'PyQt5', 'Qt', 'plugins')

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Plain text input for encryption/decryption
        self.plaintxtedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintxtedit.setGeometry(QtCore.QRect(140, 40, 201, 71))
        self.plaintxtedit.setPlainText("")
        self.plaintxtedit.setObjectName("plaintxtedit")
        
        self.plain_text = QtWidgets.QLabel(self.centralwidget)
        self.plain_text.setGeometry(QtCore.QRect(50, 50, 47, 13))
        self.plain_text.setObjectName("plain_text")
        
        # Cipher text input/output
        self.Cipher_text = QtWidgets.QLabel(self.centralwidget)
        self.Cipher_text.setGeometry(QtCore.QRect(50, 200, 61, 16))
        self.Cipher_text.setObjectName("Cipher_text")
        
        self.ciphertxtedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ciphertxtedit.setGeometry(QtCore.QRect(140, 200, 201, 71))
        self.ciphertxtedit.setObjectName("ciphertxtedit")
        
        # Encrypt and Decrypt buttons
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(150, 300, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(260, 300, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        
        # RSA Cipher label
        self.RSA_CIPHER = QtWidgets.QLabel(self.centralwidget)
        self.RSA_CIPHER.setGeometry(QtCore.QRect(360, 0, 71, 41))
        self.RSA_CIPHER.setObjectName("RSA_CIPHER")
        
        # Information and Signature fields
        self.informationtxt = QtWidgets.QLabel(self.centralwidget)
        self.informationtxt.setGeometry(QtCore.QRect(470, 40, 61, 16))
        self.informationtxt.setObjectName("informationtxt")
        
        self.sigtxt = QtWidgets.QLabel(self.centralwidget)
        self.sigtxt.setGeometry(QtCore.QRect(490, 200, 47, 13))
        self.sigtxt.setObjectName("sigtxt")
        
        self.infortxtedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.infortxtedit.setGeometry(QtCore.QRect(570, 40, 211, 71))
        self.infortxtedit.setObjectName("infortxtedit")
        
        self.sigtxtedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.sigtxtedit.setGeometry(QtCore.QRect(570, 200, 211, 71))
        self.sigtxtedit.setObjectName("sigtxtedit")
        
        # Sign and Verify buttons
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(590, 310, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(710, 310, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        
        # Generate key button
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(450, 10, 75, 23))
        self.btn_generate.setObjectName("btn_generate")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Encryption Tool"))
        self.plain_text.setText(_translate("MainWindow", "Plain Text"))
        self.Cipher_text.setText(_translate("MainWindow", "Cipher Text"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.RSA_CIPHER.setText(_translate("MainWindow", "RSA CIPHER"))
        self.informationtxt.setText(_translate("MainWindow", "Information"))
        self.sigtxt.setText(_translate("MainWindow", "Signature"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.btn_generate.setText(_translate("MainWindow", "Generate Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())